### PR TITLE
Building in container

### PR DESCRIPTION
**Pull request by ewoutp**
This change uses a docker container to build & test this library.

### CODE REVIEW

**Comment by ewoutp** [comment]
@ZeissS @zyndiecate RFR

**Comment by zyndiecate** [comment]
Why do we want/need this? What problem does it solve?

**Comment by ewoutp** [comment]
While building it, I ended up with a `client-go` file.
Turned out that was caused by having go 1.5 installed.
By running in containers we know exactly which go version to expect.

**Comment by zyndiecate** [comment]
IIWFYLGTM

**Pull request merged**
